### ISSUE TITLE
Bug: Curtains not working after firmware upgrade

### ISSUE THREAD

**Issue by donavanbecker** [futomi/node-switchbot#101]
### Describe The Bug

After upgrading to 3.9, curtains are not working

### To Reproduce

Update to 3.9

### Expected behavior

Connect Through BLE

**Comment by donavanbecker** [comment]
@mrbungle64 do you have SwitchBot Curtains?

**Comment by mrbungle64** [comment]
@donavanbecker 

No, unfortunately I do not have SwitchBot Curtains

**Comment by donavanbecker** [comment]
@mrbungle64 Sounds good. We do have a wiki that goes over the BLE API, if you make sense of any of it, like the SwitchBot lock, or or any other devices. Your help would be appreciated.

I just know the homebridge-plugin side. But I am managing most of these repos for SwitchBot (I am not an actual employee of SwitchBot).

**Comment by mrbungle64** [comment]
@donavanbecker 

Is this a staged rollout of version 3.9?
I heard from a user that the firmware version of his Curtain is still version 3.1

**Comment by donavanbecker** [comment]
@mrbungle64 im not sure.

**Comment by mrbungle64** [comment]
@donavanbecker 

Is the affected version number version 3.9 or 3.3 (or maybe both)?
Just to be sure, because I also have a report for version 3.3

Edit:
I just got information that version 3.9 is available now (User located in Germany).
In this case, the Curtain also no longer works. The previous version was 3.1

**Comment by donavanbecker** [comment]
I would think both

**Comment by mrbungle64** [comment]
@donavanbecker 

Do you know if there is a way to install a specific older version?

**Comment by donavanbecker** [comment]
I know there is a firmware recovery feature but not sure other then that.

**Comment by mrbungle64** [comment]
> I know there is a firmware recovery feature but not sure other then that.

@donavanbecker 
Where can I find this recovery feature?

**Comment by donavanbecker** [comment]
![image](https://user-images.githubusercontent.com/9875439/156225155-94fff19c-230f-40dc-813d-d86b1c76cb0a.png)

**Comment by mrbungle64** [comment]
@donavanbecker 

Thanks 👍🏻 I only looked in the device settings 😉

**Comment by donavanbecker** [comment]
@mrbungle64 resolved with #111!

**Comment by donavanbecker** [comment]
I will release a new version

**Comment by donavanbecker** [comment]
@mrbungle64 Does v1.2.0 work for you now?

**Comment by mrbungle64** [comment]
@donavanbecker 

> @mrbungle64 Does v1.2.0 work for you now?

I don't have a Curtain, but there's a report that it's [working](https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/121#issuecomment-1059444340) with v3.9, but also a report that's it's still [not working](https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/121#issuecomment-1059498958) (maybe still v3.3)
