### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by CoxieAU** [futomi/node-switchbot#139]
### Problem

Meter plus support

### Solution

Add meter plus

### Additional context

Would it be hard to extend the meter support for meter plus ?

**Comment by mrbungle64** [comment]
@CoxieAU 

The SwitchBot "Meter Plus" (WoMeterPlus) is already working with version 1.3.0

https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/175
