### ISSUE TITLE
support for the plug mini

### ISSUE THREAD

**Issue by cocoabox** [futomi/node-switchbot#140]
### Problem

Hello, I'm trying to operate the "plug mini" from nodeJS on raspberry pi 3b+ hardware. I somehow was successfully able to decode the advertisement packet (which is drastically different from any other Switchbot product) but have zero success in sending a command. The noble `Peripheral.getService()` call almost always fails with the `Failed to discover services and characteristics: DISCONNECTED` message. Sometimes the `getService()` call succeeds but returns `[]` which triggers the `No service found` error.

This seems to be RaspberryPi issue. To investigate, I have the following python code that worked several times (out of ~100 attempts). Most of the times, it fails at the `Peripheral` instantiation step.

```python
import binascii
import time
from bluepy.btle import Peripheral

print('get peripheral')

p = Peripheral('60:55:f9:35:f6:a6')

print(p)

print ('get service')
plugmini_service = p.getServiceByUUID('cba20d00-224d-11e6-9fb8-0002a5d5c51b')

print ('get characteristic')
plugmini = plugmini_service.getCharacteristics('cba20002-224d-11e6-9fb8-0002a5d5c51b')[0]

print(plugmini)

print("off")
plugmini.write(binascii.a2b_hex('570f50010100'))
time.sleep(5)

print("on")
plugmini.write(binascii.a2b_hex('570f50010180'))
time.sleep(5)

p.disconnect()
```

### Solution

My implementation can be found [here](https://github.com/cocoabox/node-switchbot/tree/add-plug-mini). `j` model Plug Mini advertisements are successfully parsed. I'm hesitant to create a pull request because first, I don't have a US plug mini , second, the `SwitchbotDeviceWoPlugMini` class doesn't work (while theoretically it *should*). I tried ~500 times in succession without any luck. 

### Additional context

I'm using a JP plug mini on Raspberry Pi3B+ hardware.

**Comment by donavanbecker** [comment]
@cocoabox Please submit a pull request. Maybe someone from SwitchBot can help us, once we merge it.

**Comment by cocoabox** [comment]
@donavanbecker Thanks! Please see https://github.com/OpenWonderLabs/node-switchbot/pull/141/
