### ISSUE TITLE
SwitchBot Humidifier Support

### ISSUE THREAD

**Issue by donavanbecker** [futomi/node-switchbot#15]
@futomi, Anyway to support the SwitchbotDevice humidifier (WoHumi)?

**Comment by donavanbecker** [comment]
FYI: [SwitchBotAPI](https://github.com/OpenWonderLabs/SwitchBotAPI)

**Comment by SwitchBot-Wonderlabs** [comment]
> FYI: [SwitchBotAPI](https://github.com/OpenWonderLabs/SwitchBotAPI)

BLE protocol is different, I will add support in the future.

**Comment by devWaves** [comment]
great work all around with the switchbot implementations!

any update on humidifier support? are the BLE calls similar to the other switchbot devices? can you please provide a byte array of the calls that can be made to a humidifier? and the bytes associated to service data 0 for status etc?

I would like to integrate humidifer with my esp32 switchbot implementation

Thanks!
