### ISSUE TITLE
Support for SwitchBot Curtain Rod 2

### ISSUE THREAD

**Issue by mrbungle64** [futomi/node-switchbot#158]
### Question

Should the library already work with SwitchBot Curtain Rod 2?

Btw.: Please create an issue template for questions and please allow multi-line text input 😉

**Comment by donavanbecker** [comment]
@mrbungle64 yes it does.

**Comment by mrbungle64** [comment]
> @mrbungle64 yes it does.

ok, thanks for quick reply 👍🏻
