### ISSUE TITLE
Motion Sensors

### ISSUE THREAD

**Issue by donavanbecker** [futomi/node-switchbot#162]
@bdraco 

An insight you can give on motion sensors to make them better for this module?

https://github.com/OpenWonderLabs/node-switchbot/blob/28338744143215e233236d8ff39635a3be1989e0/lib/switchbot-advertising.js#L250-L279

**Comment by bdraco** [comment]
What exactly are you looking for?

This is the parser the python lib is using https://github.com/Danielhiversen/pySwitchbot/blob/master/switchbot/adv_parsers/motion.py

**Comment by donavanbecker** [comment]
Just any advice you can give. Also if you can critique what is implemented currently on what we may not have correct.
