### ISSUE TITLE
TypeError: this.noble.once is not a function

### ISSUE THREAD

**Issue by mrbungle64** [futomi/node-switchbot#171]
### Analysis

Hi @donavanbecker,

with the just released version 1.9.2-17 of "@abandonware/noble" the "node-switchbot" module isn't working anymore (at least in my case).

I discovered this issue after I bumped the version of "@abandonware/noble" (and "node-switchbot") for my ioBroker adapter  ["SwitchBot (BLE) adapter for ioBroker"](https://github.com/mrbungle64/ioBroker.switchbot-ble), but I also created a sample app to reproduce it.

Maybe this is an issue in the "@abandonware/noble" module, but since the error occurs in this environment, I would like to address this issue here.

### Steps To Reproduce

Create a simple app using the sample code of the "Quick Start" section:

```js
// Load the node-switchbot and get a `Switchbot` constructor object
let Switchbot = require('node-switchbot');
// Create an `Switchbot` object
let switchbot = new Switchbot();

(async () => {
  // Start to monitor advertisement packets
  await switchbot.startScan();
  // Set an event hander
  switchbot.onadvertisement = (ad) => {
    console.log(JSON.stringify(ad, null, '  '));
  };
  // Wait 10 seconds
  await switchbot.wait(10000);
  // Stop to monitor
  switchbot.stopScan();
  process.exit();
})();
```

### Logs

```markdown
pi@raspberrypi-iobroker:/opt/iobroker/node_modules/iobroker.switchbot-ble $ node test.js 
/opt/iobroker/node_modules/iobroker.switchbot-ble/node_modules/node-switchbot/lib/switchbot.js:192
          this.noble.once("stateChange", (state) => {
                     ^

TypeError: this.noble.once is not a function
    at /opt/iobroker/node_modules/iobroker.switchbot-ble/node_modules/node-switchbot/lib/switchbot.js:192:22
    at new Promise (<anonymous>)
    at Switchbot._init (/opt/iobroker/node_modules/iobroker.switchbot-ble/node_modules/node-switchbot/lib/switchbot.js:180:19)
    at /opt/iobroker/node_modules/iobroker.switchbot-ble/node_modules/node-switchbot/lib/switchbot.js:352:12
    at new Promise (<anonymous>)
    at Switchbot.startScan (/opt/iobroker/node_modules/iobroker.switchbot-ble/node_modules/node-switchbot/lib/switchbot.js:327:19)
    at /opt/iobroker/node_modules/iobroker.switchbot-ble/test.js:8:19
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.switchbot-ble/test.js:18:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
```

### Environment

- OS: Raspberry Pi OS
- Node: v16.18.1
- npm: 8.19.2
- node-switchbot: 1.7.0

### Configuration

What `config.json` do you mean?

**Comment by mrbungle64** [comment]
I also tried with the just released version 1.9.2-18 of "@abandonware/noble", but still the same.

**Comment by donavanbecker** [comment]
@mrbungle64 Yeah I have seen this too. Thanks for reporting. I haven't had time to research, if you do find time and want to create a PR, I would merge it into beta for testing.

**Comment by donavanbecker** [comment]
@mrbungle64, looks like this is an issue with @abandonware/noble. I will push out a release of node-switchbot that will only allow -15 to be installed.

**Comment by mrbungle64** [comment]
@donavanbecker 

Thanks for the information 👍🏻 

Btw.:
Is it still necessary to @abandonware/noble install [manually](https://github.com/OpenWonderLabs/node-switchbot#installation)?

```bash
$ npm install @abandonware/noble
$ npm install node-switchbot
```

If not, I can also remove it from package.json file as a dependency in my project, right?

**Comment by donavanbecker** [comment]
node-switchbot has it as a dependency so you shouldn’t need it.

**Comment by mrbungle64** [comment]
@donavanbecker 

With version 1.7.1 I get different error now:

```
pi@raspberrypi-iobroker:/opt/iobroker/node_modules/iobroker.switchbot-ble $ node test.js 
/opt/iobroker/node_modules/iobroker.switchbot-ble/node_modules/node-switchbot/lib/switchbot.js:33
      noble = require('@abandonware/noble')({extended: false});
                                           ^

TypeError: require(...) is not a function
    at new Switchbot (/opt/iobroker/node_modules/iobroker.switchbot-ble/node_modules/node-switchbot/lib/switchbot.js:33:44)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.switchbot-ble/test.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

**Comment by donavanbecker** [comment]
v1.7.2 should fix this.

**Comment by mrbungle64** [comment]
@donavanbecker 

I checked it briefly and at first glance it looks good to me.
I will try to give you final feedback tomorrow.

**Comment by mrbungle64** [comment]
@donavanbecker 

> I checked it briefly and at first glance it looks good to me.
> I will try to give you final feedback tomorrow.

It still looks like it is working fine 👍🏻
