### ISSUE TITLE
Details about protocol

### ISSUE THREAD

**Issue by josephernest** [futomi/node-switchbot#208]
Hi,
I have a SwitchBot IP65 (SwitchBot Indoor/Outdoor Thermo-Hygrometer) : https://www.switch-bot.com/products/switchbot-indoor-outdoor-thermo-hygrometer
Is there an official documentation about the protocol / how it sends data with Bluetooth LE?

I have a little question:

When I am far from the device for 8 hours, and I come back, I notice that my phone is downloading the whole history. How does this work ? 

- Does the smartphone contact the Switchbot Thermometer via BLE and ask `GET history data since 20231208_0005`? (Is this possible? I thought BLE was only broadcasting thermometer => every device around)

- Or does the SwitchBot thermometer broadcast the whole history every minute / every x seconds ? even if no device is connected?

Thanks

**Comment by josephernest** [comment]
Is there an official documentation about the protocol and how it sends/receives data with Bluetooth LE?

**Comment by donavanbecker** [comment]
https://github.com/OpenWonderLabs/SwitchBotAPI-BLE
