### ISSUE TITLE
Useful information distributed across advertisements, discovery

### ISSUE THREAD

**Issue by echo-bravo-yahoo** [futomi/node-switchbot#210]
### Current Situation

The object returned by discover() is required to make changes to a Switchbot's state. It contains - internally - a description of the (last received?) advertisement packet, including serviceData. However, it's not exposed in a usable way - to consume this info, a customer either has to re-implement parse(advertisementData) or scan for advertisements and match them to discovered Switchbots by ID.

This is particularly important for SwitchbotWoHand, where the arm state is in the advertisement packet, but not exposed via getter.

### Proposed Change

The Switchbot object returned by discover() should make its most recently received advertisement packet available in the post-parsing format. A way to refresh these would also be useful, either by having the customer run a scan and pass the new advertisement in to the Switchbot object, or by requesting the Switchbot object run a scan to update.

**Comment by donavanbecker** [comment]
PRs are welcome
