### ISSUE TITLE
Add support for SwitchBot "Contact" and "Motion"

### ISSUE THREAD

**Issue by mrbungle64** [futomi/node-switchbot#71]
Hi @donavanbecker 

I would like to implement support for these devices in my [ioBroker Adapter](https://github.com/mrbungle64/ioBroker.switchbot-ble).

I found a related [issue](https://github.com/OpenWonderLabs/homebridge-switchbot/issues/104) in the homebridge-switchbot repo.

Many thanks in advance

**Comment by mrbungle64** [comment]
@donavanbecker 

I noticed that SwitchBot "contact" and "motion" support is basically already implemented.

Do you know if it is due to a bug that these models are not working yet, or if something is missing?

**Comment by donavanbecker** [comment]
@Minsheng, @87187, @SwitchBot, @futomi, @Devin-Wonderlabs, or @SwitchBot-Wonderlabs anyway you can help us with this?

**Comment by mrbungle64** [comment]
@donavanbecker @SwitchBot-Wonderlabs 

I created a pull request to fix this issue.

**Comment by donavanbecker** [comment]
@mrbungle64 Thanks! I will get this added to a beta and test it out.

**Comment by donavanbecker** [comment]
@mrbungle64, just tried this with homebridge-switchbot, and wasn’t able to connect.

can you confirm the latest beta works?

**Comment by mrbungle64** [comment]
@donavanbecker 

I can discover my devices with the latest beta:

```js
{
  "id": "e7216fa344a9",
  "address": "e7:21:6f:a3:44:a9",
  "rssi": -53,
  "serviceData": {
    "model": "s",
    "modelName": "WoMotion",
    "movement": false,
    "battery": 96,
    "lightLevel": "bright"
  }
}
{
  "id": "f0cda125e3ec",
  "address": "f0:cd:a1:25:e3:ec",
  "rssi": -56,
  "serviceData": {
    "model": "d",
    "modelName": "WoContact",
    "movement": false,
    "battery": 95,
    "doorState": "timeout no closed",
    "lightLevel": "bright"
  }
}
{
  "id": "ed7934d0d078",
  "address": "ed:79:34:d0:d0:78",
  "rssi": -40,
  "serviceData": {
    "model": "H",
    "modelName": "WoHand",
    "mode": false,
    "state": false,
    "battery": 91
  }
}
{
  "id": "d0775c22921c",
  "address": "d0:77:5c:22:92:1c",
  "rssi": -34,
  "serviceData": {
    "model": "T",
    "modelName": "WoSensorTH",
    "temperature": {
      "c": 17.5,
      "f": 63.5
    },
    "fahrenheit": false,
    "humidity": 51,
    "battery": 100
  }
}
```

I use this code to test this:

```js
const Switchbot = require('../lib/switchbot.js');
const switchbot = new Switchbot();

(async () => {
    // Start to monitor advertisement packets
    await switchbot.startScan();
    // Set an event handler
    switchbot.onadvertisement = (ad) => {
        console.log(JSON.stringify(ad, null, '  '));
    };
    await switchbot.wait(10000);
    // Stop to monitor
    switchbot.stopScan();
    process.exit();
})();
```

**Comment by mrbungle64** [comment]
@donavanbecker 

I also tested my ioBroker adapter with node-switchbot 1.1.3-beta.7 and it's working too.

**Comment by donavanbecker** [comment]
v1.2.0 has been released

**Comment by donavanbecker** [comment]
>``` 
> (async () => {
>     // Start to monitor advertisement packets
>     await switchbot.startScan();
>     // Set an event handler
>     switchbot.onadvertisement = (ad) => {
>         console.log(JSON.stringify(ad, null, '  '));
>     };
>     await switchbot.wait(10000);
>     // Stop to monitor
>     switchbot.stopScan();
>     process.exit();
> })();
> ```


This worked for me as well but my Mac addresses are much longer:
```
{
  "id": "4201967bda02a43f01368ee39d6b904e",
  "address": "ea:c6:da:98:d4:cc:06:1c:06:1d",
  "rssi": -71,
  "serviceData": {
    "model": "s",
    "modelName": "WoMotion",
    "movement": false,
    "battery": 99,
    "lightLevel": "dark"
  }
}
```

**Comment by mrbungle64** [comment]
@donavanbecker 

> This worked for me as well but my Mac addresses are much longer:

That's weird ... I still get correct MAC addresses:

```json
{
  "id": "f0cda125e3ec",
  "address": "f0:cd:a1:25:e3:ec",
  "rssi": -68,
  "serviceData": {
    "model": "d",
    "modelName": "WoContact",
    "movement": false,
    "battery": 91,
    "doorState": "close",
    "lightLevel": "dark"
  }
}

```

Firmware Version: V1.1 (Contact)

```json
{
  "id": "e7216fa344a9",
  "address": "e7:21:6f:a3:44:a9",
  "rssi": -65,
  "serviceData": {
    "model": "s",
    "modelName": "WoMotion",
    "movement": false,
    "battery": 92,
    "lightLevel": "dark"
  }
}

```

Firmware Version: V1.3 (Motion)

**Comment by donavanbecker** [comment]
@mrbungle64 I am on v1.3, wanna take a stab at the update?

**Comment by mrbungle64** [comment]
@donavanbecker 

> @mrbungle64 I am on v1.3, wanna take a stab at the update?

I'm also on v1.3. I had accidentally posted the data from Contact first.
I have added the correct data to my previous post.

**Comment by donavanbecker** [comment]
@mrbungle64 Weird, I wonder why I am getting the log addresses? And how to filter out to only get the data of the device I want....
